
stages:
  - build
  - release

test:
  stage: build
  image: mcr.microsoft.com/playwright:v1.22.0-focal
  script: 
    - npm ci
    - npm run test

build:
  stage: build
  image: node:lts-alpine
  script: 
    - npm ci
    - npm run build
    - >
      if [ "$CI_COMMIT_REF_NAME" == "main" ]; then
        echo "export DECK_VERSION=$(npm run --silent currentversion);" > version-vars.sh
      else
        echo "export DECK_VERSION=$(npm run --silent currentversion)-SNAPSHOT;" > version-vars.sh
      fi
    - source version-vars.sh
    - echo $DECK_VERSION
  artifacts:
    paths:
      - build/
      - version-vars.sh
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - node_modules

build docker image:
  stage: release
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  dependencies:
    - build
  before_script:
    - source $CI_PROJECT_DIR/version-vars.sh
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF}"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
      --destination "${CI_REGISTRY_IMAGE}:${DECK_VERSION}"

version bump:
  stage: release
  image: node:lts
  only:
    - main
  before_script:
    - eval `ssh-agent -s`
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null # add ssh ke
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PUBLIC_KEY" >> ~/.ssh/id_rsa.pub
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git config --global user.email "gitlab-ci@ingenhaag-tech.de"
    - git config --global user.name "Christian Ingenhaag"
    - git remote rm origin && git remote add origin git@gitlab.com:$CI_PROJECT_PATH.git
    - git fetch
    - git checkout $CI_COMMIT_REF_NAME
  script:
    - npm version patch
    - git push origin main -o ci.skip

